apiVersion: v1
kind: Pod
metadata:
    name: jumphost
    namespace: default
spec:
    containers:
    - name: jumphost
      image: ubuntu
      command:
          - sleep
          - "3600"
      imagePullPolicy: IfNotPresent
